version: 0.2

environment_variables:
  plaintext:
    S3_BUCKET: "songodb.io/docs/api"
    CLOUDFRONT_DISTRIBUTION_ID: "E7C381K3UGYB0"
    FRONTEND_ENV: "prod"

phases:
  install:
    commands:
      - bundle install 
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - echo Build CODEBUILD_SOURCE_VERSION $CODEBUILD_SOURCE_VERSION
      - echo Build CODEBUILD_SRC_DIR $CODEBUILD_SRC_DIR
      - echo Build CODEBUILD_BUILD_NUMBER $CODEBUILD_BUILD_NUMBER
      - echo Build CODEBUILD_START_TIME $CODEBUILD_START_TIME
      - bundle exec middleman build --clean
  post_build:
    commands:
      - aws s3 cp $CODEBUILD_SRC_DIR/build/javascripts/ s3://$S3_BUCKET/javascripts/ --acl public-read --recursive --cache-control 'max-age=31104000'
      - aws s3 cp $CODEBUILD_SRC_DIR/build/stylesheets/ s3://$S3_BUCKET/stylesheets/ --acl public-read --recursive --cache-control 'max-age=31104000'
      - aws s3 cp $CODEBUILD_SRC_DIR/build/images/ s3://$S3_BUCKET/images/ --acl public-read --recursive --cache-control 'max-age=31104000'
      - aws s3 cp $CODEBUILD_SRC_DIR/build/fonts/ s3://$S3_BUCKET/fonts/ --acl public-read --recursive --cache-control 'max-age=31104000'
      - aws s3 cp $CODEBUILD_SRC_DIR/build/index.html s3://$S3_BUCKET/index.html --acl public-read --cache-control max-age=0,no-cache,no-store,must-revalidate
      # - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*" 